version: 2
updates:
  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    groups:
      # Group everything except major version updates
      # and security vulnerabilities together
      regular-updates:
        update-types:
          - 'minor'
          - 'patch'

  # Docker
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 7

  # Ruby dependencies
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
