inherit_gem:
  citizens-advice-style:
    - default.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Metrics/MethodLength:
  Max: 12
