inherit_gem:
  citizens-advice-style:
    - default.yml
    - default-rails.yml

AllCops:
  TargetRubyVersion: 3.2

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
