# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby
# https://github.com/ruby/setup-ruby

name: Test and lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.4', '3.3', '3.2']
        rails: ['8.0', '7.2']
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Install rails
        run: bundle add activemodel --version "~> ${{ matrix.rails }}"
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
